[package]
org = "commons"
name = "timeplus"
version = "0.2.2"
distribution = "2201.12.9"
authors = ["Hasitha Aravinda"]
keywords = ["time", "datetime", "timezones", "time-formatting", "time-parsing"]
repository = "https://github.com/bal-tips/module-commons-timeplus"
icon = "icon.png"
license = ["Apache-2.0"]

[platform.java21]
graalvmCompatible = true